package client.ui;

import server.SystemController;

/*
 * Graphical User Interface of the application.
 * Generates events which are dispatched to a controller.
 */
public class GUI {
	
	/*
	 * Updates that the GUI supports.
	 */
	public interface GUIUpdate{
		
	}
	
	/*
	 * Controller who is going to receive the events
	 * generated by the GUI.
	 */
	SystemController controller;
	
	
}
